### ISSUE TITLE
Port to gnome 3.20

### ISSUE THREAD

**Issue by elvisd** [BrOrlandi/Desktop-Scroller-GNOME-Extension#16]

**Comment by thoemy** [comment]
Until the updated version is available through extensions.gnome.org you can edit `$HOME/.local/share/gnome-shell/extensions/desktop-scroller@brorlandi/metadata.json` and simply add the version. Restart gnome-shell afterwards.

**Comment by elvisd** [comment]
Thank you. I'll do it :+1:

**Comment by BrOrlandi** [comment]
Updated.

https://extensions.gnome.org/extension/561/desktop-scroller-all-sides-for-gnome-36/
