### ISSUE TITLE
Scroll on ubuntu 16.04 doesn't work anymore

### ISSUE THREAD

**Issue by Aleksandaar** [BrOrlandi/Desktop-Scroller-GNOME-Extension#19]
If you enable edges, for example - top edge, and you try to scroll to the next workspace, in gnome 16.04 it just displays a notification on the screen like the workspace is being changed, but it actually doesn't change the workspace, it just does nothing.

**Comment by thoemy** [comment]
I'm not using Ubuntu. But 16.04 seems to ship with gnome-shell 3.18 which should work. Did it work before?

**Comment by Aleksandaar** [comment]
@thoemy No, it didn't used to work. I have installed two Ubuntu 16.04 LTS or more precise GNOME 3, (GNOME Shell 3.18.5), on two different computers and it didn't work on both of them on a clean installation of the system. It used to work on Ubuntu 14.04, but in Ubuntu 16.04 it stopped working.

**Comment by thoemy** [comment]
Closing since Ubuntu 16.04 is now deprecated by two newer LTS releases. Sorry for not fixing it back then.
