### ISSUE TITLE
Scroll doesn't work after changing the wallpaper

### ISSUE THREAD

**Issue by elvisd** [BrOrlandi/Desktop-Scroller-GNOME-Extension#21]
After changing the wallpaper image the desktop scroll doesn't work anymore.
After a Alt+F2 & r (restarting gnome shell) everything works as expected

**Comment by BrOrlandi** [comment]
Hi, I couldn't reproduce it here.

Which version of SO you are using and GNOME Shell version.

Thanks

**Comment by elvisd** [comment]
I'm using Arch (4.16.6-1-ARCH) with GNOME 3.28.1 and setting my wallpaper using The GNOME image viewer 3.28.1.

**Comment by BrOrlandi** [comment]
I checked here, only the desktop scroll is not working when the wallpaper changes.
The edge scroll still working.

**Comment by elvisd** [comment]
As stated in the issue description is the desktop scroll isn't working.

**Comment by thoemy** [comment]
Hi @elvisd,
please test the new version and report back. Just copy the [extension.js](https://raw.githubusercontent.com/BrOrlandi/Desktop-Scroller-GNOME-Extension/master/extension.js) to `$HOME/.local/share/gnome-shell/extensions/desktop-scroller@brorlandi/extension.js`.

**Comment by elvisd** [comment]
hi @thoemy I confirm you that the desktop scrolling works as expected. Nice! Well done.
