### ISSUE TITLE
Workspace switching doesn't works when scrolling over the wallpaper.

### ISSUE THREAD

**Issue by lapega** [BrOrlandi/Desktop-Scroller-GNOME-Extension#22]
Ubuntu 18.04 here, works ok on edge scrolling but won't switch workspaces when I scroll over the wallpaper (I have that option enabled).

I've tried:
 - disable/enable the option
 - Alt + F2 / r
 - Uninstall/reinstall the extension

**Comment by thoemy** [comment]
Do you have the desktop icons enabled? See #20.

**Comment by lapega** [comment]
Yes, I think is set by default in Ubuntu

**Comment by pehlm** [comment]
Same here, Ubuntu 18.04, desktop icons enabled, edge switching is working but not wallpaper scroll. Works if I disable icons on desktop. Hope you can fix it, I don't want to disable icons. Using edge scrolling now for the time being.

**Comment by thoemy** [comment]
Closing in favor of #20
