### ISSUE TITLE
Doesn't work in Gnome 3.30

### ISSUE THREAD

**Issue by AlexWayfer** [BrOrlandi/Desktop-Scroller-GNOME-Extension#24]
I see no errors, settings of extension are opening. But scroll over wallpaper do nothing.

**Comment by thoemy** [comment]
See #23 

You can make the changes in `~/.local/share/gnome-shell/extensions/desktop-scroller@brorlandi` and restart Gnome Shell

**Comment by AlexWayfer** [comment]
Oh, sorry, I searched for a relevant issue, not PR.
