### ISSUE TITLE
[BUG] Doesn't work on gnome 3.34.1

### ISSUE THREAD

**Issue by lonix1** [BrOrlandi/Desktop-Scroller-GNOME-Extension#27]
ubuntu 19.10
gnome 3.34.1

**Comment by prkos** [comment]
The same on Ubuntu 19.10 GNOME 3.34.4

**Comment by thoemy** [comment]
I'm pretty sure it should work with Gnome 3.34. Could it be #20 ?

**Comment by lonix1** [comment]
Works on ubuntu 20.04
Thanks
